# @Author: cyril.gratecos.ext
# @Date:   2017-05-08T22:16:31+02:00
# @Last modified by:   cyril.gratecos.ext
# @Last modified time: 2017-05-09T00:04:40+02:00



baseurl = "https://delaballe.github.io/fcu-ansible-examples/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "fcu-Ansible"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Provision & Deploy with Ansible on the Outscale® Cloud Platform"
  logo = "img/outscale+ansible.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Cyril Gratecos"
  email = "cyril.gratecos@gmail.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "delaballe"
  #twitter = "username"
  #reddit = "username"
  linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"


[[menu.main]]
    name = "Install"
    url = "page/install"
    weight = 1

[[menu.main]]
    parent = "examples"
    name = "Big Image Sample"
    url = "post/2017-03-07-bigimg-sample"
    weight = 1

[[menu.main]]
    parent = "examples"
    name = "Math Sample"
    url = "post/2017-03-05-math-sample"
    weight = 2

[[menu.main]]
    parent = "examples"
    name = "Code Sample"
    url = "post/2016-03-08-code-sample"
    weight = 3
